apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-data-pvc
  namespace: mattermost
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi  # Increased from 5+2+1=8Gi to accommodate logs + plugins
